### ISSUE TITLE
Evaluation stuck at (Gym <-> OMNeTpp) socket connection

### ISSUE THREAD

**Issue by daewookhwang** [NVlabs/RLCC#1]
Hi, I am interested in your work and trying to run some simulations. I followed the guide and saw that training and evaluating on ADPG works without problem.

First, I have a question: Does your code implementation on other models than ADPG (such as DQN and PPO) also supports evaluation?

I am asking because their (DQN,PPO) test part source code structure seems a bit different to ADPG. I modified the __init__ part in DQN class. I added below 4 lines of code:

```
        if self.config.agent.evaluate:
            self.load_model()
                
        if self.config.logging.wandb is not None:
            self.config.logging.wandb.watch(self.model, log=None, log_freq=1000)
```

To load the model and test it. And I also added

`        self.save_model(checkpoint=timesteps)`

At the last line of train() function.

After training and saving one DQN model, I run the test with below command:

`root@26bc11de9adf:/workspace/RLCC/reinforcement_learning# python3 run.py --envs_per_scenario 1  --learning_rate 0.01 --history_length 2 --agent DQN --scenarios 64_128_m2o_eval --save_name "dw_test_dqn" --agent_features action bandwidth --config dqn --evaluate`

However it's stuck in line

`        fd, addr = self._accept()`

in receive_data(). It seems that the Gym(server) and OMNeTpp subprocess are supposed to communicating with sockets, but their socket connection is not done. 

In the case of ADPG, after the connection to OMNeTpp is done, on the terminal it prints out

```
OMNEST Discrete Event Simulation  (C) 1992-2014 Andras Varga, OpenSim Ltd.
Version: 4.6, build: 141202-f785492, edition: Commercial Edition
See the license for distribution terms and warranty disclaimer
Setting up Cmdenv...
Loading NED files from ../ned/algo/: 2
Loading NED files from ../ned/prog_cc: 23
Loading NED files from ../ned/dctg/: 2
....
```

But these lines are not showing up in testing DQN and PPO.

Do you have any idea why it's stuck at socket connection?

**Comment by codefan-byte** [comment]
Hello @daewookhwang 

How did you solve the problem?
